- name: "VSCode | Assert input variable"
  ansible.utils.validate:
    data: "{{ vscode }}"
    criteria: "{{ lookup('file', 'assertions/criteria/vscode-criteria.json') | from_json }}"
    engine: ansible.utils.jsonschema
  run_once: yes
  delegate_to: localhost

- name: "VSCode | Gather package facts"
  ansible.builtin.package_facts:
    manager: "auto"
  when:
    - vscode.gather_facts is not defined or vscode.gather_facts

- name: "VSCode | Download and install"
  ansible.builtin.include_tasks: install.yml
  when:
    - "'code' not in ansible_facts.packages"
    - vscode.remove is undefined or not vscode.remove

- name: "VSCode | Remove client"
  ansible.builtin.apt:
    name: "code"
    state: absent
  when:
    - vscode.remove is defined
    - vscode.remove
